method: rs  # (Augmented) random search.

out_dir: './experiments/synthetic_experiments/110620/rs_optimize/'

# Either choose max_iterations or max_objective_calls unequal None.
max_iterations: 
max_objective_calls: 300

optimizer_config:
    step_size: 0.02
    samples_per_iteration: variable  # 1+dim//8
    exploration_noise: 0.01
    standard_deviation_scaling: True
    num_top_directions:
    param_args_ignore: 
