out_dir : './experiments/synthetic_experiments/ablation/'
dimensions : [12, 24, 36]
num_objectives : 40
num_samples : 1000
noise_variance : 0.01
factor_lengthscale : 2
gamma : 0.3
gp_hypers: 
    outputscale: 1.
n_max: 15
